server:
  port: 8081

spring:
  application:
    name: im-netty
  redis:
    host: localhost
    port: 6379
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

netty:
  port: 8080
  boss-threads: 1
  worker-threads: 16
  server:
    path: /im/netty/servers

zookeeper:
  address: localhost:2181
  session-timeout: 60000
  connection-timeout: 5000

message:
  max-size: 10485760
  queue-size: 10000
  thread-pool-size: 10